### PR TITLE
Optional upload url for release events

### PR DESCRIPTION
**Pull request by CurtisHughes**
This would allow users to upload assets to a release without providing an upload url. 

It uses the Github context to determine if the action was a [release-event-release](https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release) (i.e. published, deleted, prereleased) and fetches the upload url based on the current actions release id.

```yaml
on:
  release:
    types:
      - published

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          zip --junk-paths my-artifact README.md
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
```

### CODE REVIEW

**Comment by liuchong** [comment]
I need this, actually I've made a similar change and then found this pull request 😹
Please merge 👀

**Comment by liuchong** [comment]
I provided my solution, any one is ok for me to merge: https://github.com/actions/upload-release-asset/pull/45

**Comment by giansalex** [comment]
Is very usefull

**Comment by clementlecorre** [comment]
I need this too! 👍

**Pull request closed without merging**
